name: Portfolio Deployment

on:
  push:
   branches:
      - main
 on:
  pull_request:
    branches:
      - main
      -isha
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
