name: Portfolio Deployment

on:
  push:
    branches:
      - main
      - isha # Add any other branches you want to deploy on push
      - feature/**
  pull_request:
    branches:
      - main
      - isha # Add any other branches you want to deploy on pull request creation
      - feature/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
